# Generated by Django 4.1.7 on 2023-05-24 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0006_survey_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meals', models.IntegerField(blank=True, null=True)),
                ('beef', models.BooleanField(default=False)),
                ('chicken', models.BooleanField(default=False)),
                ('fish', models.BooleanField(default=False)),
                ('seafood', models.BooleanField(default=False)),
                ('sleep', models.CharField(blank=True, max_length=20, null=True)),
                ('activity', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
