# Generated by Django 4.1.7 on 2023-05-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_dietplan_delete_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietplan',
            old_name='food',
            new_name='Breakfast',
        ),
        migrations.RenameField(
            model_name='dietplan',
            old_name='calories',
            new_name='Dinner',
        ),
        migrations.RenameField(
            model_name='dietplan',
            old_name='carbs',
            new_name='Lunch',
        ),
        migrations.RenameField(
            model_name='dietplan',
            old_name='portion_size',
            new_name='Snack',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='desired_weight',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='protein',
        ),
    ]
