# Generated by Django 4.1.7 on 2023-05-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_food_dietplan_breakfast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='meal',
        ),
    ]
