# Generated by Django 4.1.7 on 2023-05-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_dietplan_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='Breakfast',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='Dinner',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='Lunch',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='Snack',
            field=models.CharField(max_length=500),
        ),
    ]
